export type DoxygenPageBool = "yes" | "no"

export type DoxygenPageGraphRelation
  = | "include"
    | "usage"
    | "template-instance"
    | "public-inheritance"
    | "protected-inheritance"
    | "private-inheritance"
    | "type-constraint"

export type DoxygenPageRefKind = "compound" | "member"

export type DoxygenPageMemberKind
  = | "define"
    | "property"
    | "event"
    | "variable"
    | "typedef"
    | "enum"
    | "function"
    | "signal"
    | "prototype"
    | "friend"
    | "dcop"
    | "slot"
    | "interface"
    | "service"

export type DoxygenPageProtectionKind
  = | "public"
    | "protected"
    | "private"
    | "package"

export type DoxygenPageRefQualifierKind = "lvalue" | "rvalue"

export type DoxygenPageLanguage
  = | "Unknown"
    | "IDL"
    | "Java"
    | "C#"
    | "D"
    | "PHP"
    | "Objective-C"
    | "C++"
    | "JavaScript"
    | "Python"
    | "Fortran"
    | "VHDL"
    | "XML"
    | "SQL"
    | "Markdown"
    | "Slice"
    | "Lex"

export type DoxygenPageVirtualKind
  = | "non-virtual"
    | "virtual"
    | "pure-virtual"

export type DoxygenPageCompoundKind
  = | "class"
    | "struct"
    | "union"
    | "interface"
    | "protocol"
    | "category"
    | "exception"
    | "service"
    | "singleton"
    | "module"
    | "type"
    | "file"
    | "namespace"
    | "group"
    | "page"
    | "example"
    | "dir"
    | "concept"

export type DoxygenPageSectionKind
  = | "user-defined"
    | "public-type"
    | "public-func"
    | "public-attrib"
    | "public-slot"
    | "signal"
    | "dcop-func"
    | "property"
    | "event"
    | "public-static-func"
    | "public-static-attrib"
    | "protected-type"
    | "protected-func"
    | "protected-attrib"
    | "protected-slot"
    | "protected-static-func"
    | "protected-static-attrib"
    | "package-type"
    | "package-func"
    | "package-attrib"
    | "package-static-func"
    | "package-static-attrib"
    | "private-type"
    | "private-func"
    | "private-attrib"
    | "private-slot"
    | "private-static-func"
    | "private-static-attrib"
    | "friend"
    | "related"
    | "define"
    | "prototype"
    | "typedef"
    | "enum"
    | "func"
    | "var"

export type DoxygenPageHighlightClass
  = | "comment"
    | "normal"
    | "preprocessor"
    | "keyword"
    | "keywordtype"
    | "keywordflow"
    | "stringliteral"
    | "xmlcdata"
    | "charliteral"
    | "vhdlkeyword"
    | "vhdllogic"
    | "vhdlchar"
    | "vhdldigit"

export type DoxygenPageSimpleSectKind
  = | "see"
    | "return"
    | "author"
    | "authors"
    | "version"
    | "since"
    | "date"
    | "note"
    | "warning"
    | "pre"
    | "post"
    | "copyright"
    | "invariant"
    | "remark"
    | "attention"
    | "important"
    | "par"
    | "rcs"

export type DoxygenPageCheck = "checked" | "unchecked"

export type DoxygenPageVersionNumber = string

export type DoxygenPageImageKind
  = | "html"
    | "latex"
    | "docbook"
    | "rtf"
    | "xml"

export type DoxygenPagePlantumlEngine
  = | "uml"
    | "bpm"
    | "wire"
    | "dot"
    | "ditaa"
    | "salt"
    | "math"
    | "latex"
    | "gantt"
    | "mindmap"
    | "wbs"
    | "yaml"
    | "creole"
    | "json"
    | "flow"
    | "board"
    | "git"
    | "hcl"
    | "regex"
    | "ebnf"
    | "files"

export type DoxygenPageParamListKind
  = | "param"
    | "retval"
    | "exception"
    | "templateparam"

export type DoxygenPageCharRange = string

export type DoxygenPageParamDir = "in" | "out" | "inout"

export type DoxygenPageAccessor
  = | "retain"
    | "copy"
    | "assign"
    | "weak"
    | "strong"
    | "unretained"

export type DoxygenPageAlign = "left" | "right" | "center"

export type DoxygenPageVerticalAlign = "bottom" | "top" | "middle"

export type DoxygenPageOl = "1" | "a" | "A" | "i" | "I"
