name: 🐛 Bug Report (User)
description: Report a bug encountered while using the library
title: "[Bug]: "
labels: [bug, user-report]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for using the library and taking the time to report a bug. Please fill out the following information so we can assist you more effectively.

  - type: input
    id: package-version
    attributes:
      label: Library Version
      description: Check your `package.json`.
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the issue you're experiencing.
      placeholder: "When I use the X feature with Y input, I get unexpected output..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Help us reproduce the bug.
      placeholder: |
        1. Install the package
        2. Use the following code snippet
        3. See the error/output
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us what you expected to happen.
      placeholder: I expected the document to render with...

  - type: textarea
    id: actual-output
    attributes:
      label: Actual Output
      description: If applicable, paste the output or error message.
      placeholder: "Received error: TypeError: undefined is not a function..."

  - type: textarea
    id: environment
    attributes:
      label: Environment Info
      description: |
        Provide details about your environment (Bun/Node.js version, OS, etc.).
      placeholder: |
        - OS: Windows 11 / macOS 14 / Ubuntu 22.04
        - Bun/Node.js version: 18.x
        - Package manager: bun / npm / yarn / pnpm

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](./?tab=coc-ov-file)
          required: true
